name: finance
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  flutter_native_splash: ^2.4.3
  toastification: ^2.3.0
  flutter_svg: ^2.0.16
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  fl_chart: ^0.69.2
  flutter_speed_dial: ^7.0.0
  icons_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  image: assets/logo/Dlogo.png
  color: "#E4E4E4"
  image_dark: assets/logo/Llogo.png
  color_dark: "#36343A"
  
  android_12:
    image: assets/logo/Dlogo.png
    icon_background_color: "#E4E4E4"
    image_dark: assets/logo/Llogo
    icon_background_color_dark: "#36343A"

  web: false

icons_launcher:
  image_path: "assets/logo/appIcon/DIcon.jpg"
  platforms:
    android:
      enable: true
      image_path: "assets/logo/appIcon/DIcon.jpg"
      notification_image: "assets/logo/appIcon/DIcon.jpg"
      adaptive_background_image: "assets/logo/appIcon/DIcon.jpg"
      adaptive_foreground_image: "assets/logo/appIcon/DIcon.jpg"
      adaptive_round_image: "assets/logo/appIcon/DIcon.jpg"
      adaptive_monochrome_image: "assets/logo/appIcon/DIcon.jpg"
    ios:
      enable: true
      image_path: "assets/logo/appIcon/DIcon.jpg"
      # For iOS 18+ (support dark and tinted)
      dark_path: "assets/logo/appIcon/DIcon.jpg"
      tinted_path: "assets/logo/appIcon/DIcon.jpg"

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/appIcon/DIcon.jpg
    - assets/logo/Dlogo.png
    - assets/logo/Llogo.png
    - assets/icons/icon-money.png
    - assets/icons/arrow-up.svg
    - assets/icons/arrow-down.svg
    - assets/icons/DSort.svg
    - assets/icons/LSort.svg
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
