name: finance
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  flutter_native_splash: ^2.4.3
  isar: ^3.1.0+1
  toastification: ^2.3.0
  flutter_svg: ^2.0.16
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  fl_chart: ^0.69.2
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  image: assets/logo/Dlogo.png
  color: "#E4E4E4"
  image_dark: assets/logo/Llogo.png
  color_dark: "#36343A"
  
  android_12:
    image: assets/icons/Dlogo.png
    icon_background_color: "#E4E4E4"
    image_dark: assets/icons/Llogo
    icon_background_color_dark: "#36343A"

  web: false

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/Dlogo.png
    - assets/logo/Llogo.png
    - assets/icons/icon-money.png
    - assets/icons/arrow-up.svg
    - assets/icons/arrow-down.svg
    - assets/icons/DSort.svg
    - assets/icons/LSort.svg
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
